[package]
authors = ["roblabla <unfiltered@roblab.la>"]
name = "libtransistor"
version = "0.0.0"

[dependencies]

[dependencies.libtransistor-sys]
optional = false
path = "../libtransistor-sys/"

[dependencies.ralloc]
optional = false
version = "1.0.0"
default-features = false
