[package]
authors = ["roblabla <unfiltered@roblab.la>"]
name = "libtransistor-sys"
version = "0.0.0"

[build-dependencies.bindgen]
git = "https://github.com/rust-lang-nursery/rust-bindgen"

[dependencies]
cty = "0.1.5"
